main/urls.py
from django.urls import path
from .views import PostListView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView
from . import views


app_name = 'main'

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('random/', views.random_request, name='random'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
]

memesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, docuement_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    class Meta:
        ordering = ['-id']
    post_title = models.CharField(max_length=75, unique=True)
    post_content = models.TextField(blank=True, default='')
    post_image = models.ImageField(upload_to='pics')
    post_published = models.DateTimeField('date published', auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse('main:post-detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Comment {self.body} by {self.comment_author.username}'

main/forms.py
from .models import Comment
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
import random
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from datetime import datetime, timezone
from .forms import CommentForm


class PostListView(ListView):
    model = Post
    template_name = 'main/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'Posts'
    ordering = ['-post_published']
    paginate_by = 5

    #  this func is to replace the datetime format and give back a more user friendly format
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = Post.objects.all()
        for post in posts:
            temp = datetime.now(timezone.utc) - post.post_published
            time_difference = temp.total_seconds()
            if time_difference < 59:
                post.post_published = 'just now'
            elif 59 < time_difference < 3599:
                post.post_published = f'{int(time_difference / 60)} minutes ago'
            elif 3599 < time_difference < 86399:
                post.post_published = f'{int(time_difference / 3600)} hours ago'
            elif 86399 < time_difference < 604799:
                if 86399 < time_difference < 172799:
                    post.post_published = 'a day ago'
                elif 172799 < time_difference < 259199:
                    post.post_published = 'two days ago'
                elif 259199 < time_difference < 345599:
                    post.post_published = 'three days ago'
                elif 345599 < time_difference < 431999:
                    post.post_published = 'four days ago'
                elif 431999 < time_difference < 518399:
                    post.post_published = 'fifth days ago'
                elif 518399 < time_difference < 604799:
                    post.post_published = 'six days ago'
            elif 604799 < time_difference < 2419199:
                if 604799 < time_difference < 1209599:
                    post.post_published = 'a week ago'
                elif 1209599 < time_difference < 1814399:
                    post.post_published = 'two weeks ago'
                elif 1814399 < time_difference < 2419199:
                    post.post_published = 'three weeks ago'
            elif 2591999 < time_difference < 5183999:
                post.post_published = 'a month ago'
            elif 5183999 < time_difference < 7775999:
                post.post_published = 'two months ago'
            elif 7775999 < time_difference < 15551999:
                post.post_published = 'six months ago'
            elif 15551999 < time_difference < 31103999:
                post.post_published = ' a year ago'
            elif 31103999 < time_difference:
                post.post_published = 'long ago'

        p = Paginator(posts, self.paginate_by)
        context['Posts'] = p.page(context['page_obj'].number)
        return context


class UserPostListView(ListView):
    model = Post
    template_name = 'main/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'Posts'
    paginate_by = 5

    def get_queryset(self, **kwargs):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        posts = Post.objects.filter(created_by=user).order_by('-post_published')
        #  this func is to replace the datetime format and give back a more user friendly format
        for post in posts:
            post.post_published = datetime.now(timezone.utc) - post.post_published
            time_difference = post.post_published.total_seconds()
            if time_difference < 59:
                post.post_published = 'just now'
            elif 59 < time_difference < 3599:
                post.post_published = f'{int(time_difference / 60)} minutes ago'
            elif 3599 < time_difference < 86399:
                post.post_published = f'{int(time_difference / 3600)} hours ago'
            elif 86399 < time_difference < 604799:
                if 86399 < time_difference < 172799:
                    post.post_published = 'a day ago'
                elif 172799 < time_difference < 259199:
                    post.post_published = 'two days ago'
                elif 259199 < time_difference < 345599:
                    post.post_published = 'three days ago'
                elif 345599 < time_difference < 431999:
                    post.post_published = 'four days ago'
                elif 431999 < time_difference < 518399:
                    post.post_published = 'fifth days ago'
                elif 518399 < time_difference < 604799:
                    post.post_published = 'six days ago'
            elif 604799 < time_difference < 2419199:
                if 604799 < time_difference < 1209599:
                    post.post_published = 'a week ago'
                elif 1209599 < time_difference < 1814399:
                    post.post_published = 'two weeks ago'
                elif 1814399 < time_difference < 2419199:
                    post.post_published = 'three weeks ago'
            elif 2591999 < time_difference < 5183999:
                post.post_published = 'a month ago'
            elif 5183999 < time_difference < 7775999:
                post.post_published = 'two months ago'
            elif 7775999 < time_difference < 15551999:
                post.post_published = 'six months ago'
            elif 15551999 < time_difference < 31103999:
                post.post_published = ' a year ago'
            elif 31103999 < time_difference:
                post.post_published = 'long ago'

        return posts


def post_detail(request, **kwargs):
    template_name = 'main/post_detail.html'
    post = get_object_or_404(Post, id=kwargs['pk'])
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            new_comment.comment_author = post.created_by
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'object': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form,
                                           'post_username': post.created_by.username})


# Enables the user to create a post
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['post_title', 'post_content', 'post_image']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['post_title', 'post_content', 'post_image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


# gives back a random post
def random_request(request):
    return render(request=request,
                  template_name='main/random.html',
                  context={'Post': Post.objects.get(id=random.randint(1, len(Post.objects.values_list('id'))))
                           })

main/templates/main/add.html
{% extends 'main/header.html' %}
{% block content %}
    <br>
    <form enctype="multipart/form-data" method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}

        <button  class="btn btn-outline-info" type="submit">Post</button>

    </form>

{% endblock %}

main/templates/main/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main/main.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'main/logo.png' %}"/>
    {% if title %}
    <title>Memesite - {{ title }}</title>
    {% else %}
    <title>Memesite</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'main:home' %}">Memesite</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'main:home' %}">Home</a>
                    <a class="nav-item nav-link" href="{% url 'main:random' %}">Random</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'main:post-create' %}">Create Post</a>
                    <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
                </p>
            </div>
        </div>
    </div>
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/home.html
{% extends 'main/header.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    {% for post in Posts %}
      <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.created_by.profile.image.url }}">
          <div class="media-body">
              <div class="article-metadata">
                  <a class="mr-2" href="{% url 'main:user-posts' post.created_by.username %}">{{ post.created_by }}</a>
                  {% if post.post_published == "just now" %}
                    <span style="color:#00ed3f;" class="error_number">&bull;</span>
                    <small class="text-muted">{{ post.post_published }}</small>
                  {% else %}
                    <small class="text-muted">{{ post.post_published }}</small>
                  {% endif %}
              </div>
              <h2><a class="article-title" href="{% url 'main:post-detail' post.id %}">{{ post.post_title }}</a></h2>
              <p class="article-content">{{ post.post_content }}</p>
              <img src="/media/{{ post.post_image }}" alt="{{ post.post_image }}" height="400" width="400">
          </div>
          <h7>Comments: {{ post.comments.count }}</h7>
      </article>
      {% endfor %}
  </div>

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">&laquo; First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{num}}"> {{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}"> {{ num }} </a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}"> Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
{% endblock %}

main/templates/main/post_confirm_delete.html
{% extends 'main/header.html' %}
{% block content %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group" enctype="multipart/form-data">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the post "{{ object.title }}" ?</h2>
        </fieldset>
        <div class="form-group">
            <button  class="btn btn-outline-danger" type="submit">Yes delete</button>
            <a  class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

main/templates/main/post_detail.html
{% extends 'main/header.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ object.created_by.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'main:user-posts' post_username %}">{{ object.created_by }}</a>
                <small class="text-muted">{{ object.post_published }}</small>
                {% if object.created_by == user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'main:post-update' object.id%}">Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'main:post-delete' object.id%}">Delete</a>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ object.post_title }}</h2>
            <p class="article-content">{{ object.post_content }}</p>
            <img src="/media/{{ object.post_image }}" alt="{{ object.post_image }}" height="400" width="400">
        </div>
    </article>
    {% for comment in comments %}
    <div class="comments" style="padding: 10px;">
        <p class="font-weight-bold">
            {{ comment.comment_author }}
            <span class=" text-muted font-weight-normal">
                  {{ comment.created_on }}
                </span>
        </p>
        {{ comment.body | linebreaks }}
    </div>
    {% endfor %}
    <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
            Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
            {{ comment_form | crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/post_form.html
{% extends 'main/header.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group" enctype="multipart/form-data">
                <legend class="border-bottom mb-4">Meme</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
            <button  class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock %}

main/templates/main/random.html
{% extends 'main/header.html' %}
{% block content %}


<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ Post.created_by.profile.image.url }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="#">{{ Post.created_by }}</a>
      <small class="text-muted">{{ Post.post_published }}</small>
    </div>
    <h2><a class="article-title" href="{% url 'main:post-detail' Post.id %}">{{ Post.post_title }}</a></h2>
    <p class="article-content">{{ Post.post_content }}</p>
    <img src="/media/{{ Post.post_image }}" alt="{{ Post.post_image }}" height="400" width="400">
  </div>
</article>
{% endblock %}

main/templates/main/user_posts.html
{% extends 'main/header.html' %}

{% block content %}
<div class="row">
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in Posts %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ post.created_by.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'main:user-posts' post.created_by.username %}">{{ post.created_by }}</a>
                <small class="text-muted">{{ post.post_published }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'main:post-detail' post.id %}">{{ post.post_title }}</a></h2>
            <p class="article-content">{{ post.post_content }}</p>
            <img src="/media/{{ post.post_image }}" alt="{{ post.post_image }}" height="400" width="400">
        </div>
    </article>
    {% endfor %}
</div>

{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}
{% endblock %}